import type { Metadata } from "next";
import SmoothScroll from "@/components/ui/SmoothScroll";
import localFont from "next/font/local";
import "./globals.css";

const quadrillion = localFont({
  src: [
    {
      path: './fonts/quadrillion/Quadrillion Sb.otf',
      weight: '600', // SemiBold
      style: 'normal',
    },
    {
      path: './fonts/quadrillion/Quadrillion Sb It.otf',
      weight: '600', // SemiBold Italic
      style: 'italic',
    },
  ],
  variable: '--font-quadrillion',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${quadrillion.variable} h-full antialiased`}
    >
      <body>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
